export const FETCH_GRAPHICS_START = 'FETCH_GRAPHICS_START';
export const FETCH_GRAPHICS_SUCCESS = 'FETCH_GRAPHICS_SUCCESS';
export const FETCH_GRAPHICS_FAIL = 'FETCH_GRAPHICS_FAIL';

export const TOGGLE_CUSTOM_LAYOUT = 'TOGGLE_CUSTOM_LAYOUT';

export const CHANGE_EXPRESSION = 'CHANGE_EXPRESSION';
